name: Tests
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        node_version: [12, 13, 14, 15, 16]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm ci
      - run: npm test
      - run: npm audit
